### PR TITLE
Screen 10 - Turn Off BitLocker

### PR DESCRIPTION
**Pull request by charafau**
Implemented screen 10 design 

image

issue: https://github.com/canonical/ubuntu-desktop-installer/issues/35

### CODE REVIEW

**Comment by charafau** [comment]
@oSoMoN should I also move this one to wizard wiget?

**Comment by oSoMoN** [comment]
> @oSoMoN should I also move this one to wizard wiget?

Sorry I missed that one. Please do, and please rebase on the latest main. Thanks!

**Comment by jpnurmi** [comment]
Looks very similar to the [Turn off RST](https://github.com/canonical/ubuntu-desktop-installer/issues/28) page. Would it be worth to share the layout?

**Comment by charafau** [comment]
I can change the code accordingly, just someone needs to merge the other one so we won't end up with PR mess :)

**Comment by jpnurmi** [comment]
I'd like to pull my words back. :smile: I think the page is going to be so simple after basing it on `WizardPage` (which already has title, header, and content properties) that it's probably not worth it to start creating some common page class for these...

**Comment by jpnurmi** [comment]
Rebasing and adapting to `WizardPage` & `Wizard.of(context).next/back()` should be enough to get this going.

**Comment by charafau** [comment]
Should be good to go now :+1:

**Comment by jpnurmi** [comment]
Thanks! I defined the page route for testing purposes and removed superfluous `Container` and `Padding` widgets. There was accidental double padding after migrating to `WizardPage`.

**Review by jpnurmi — APPROVED** [review]
LGTM :+1:

**Pull request merged**
