### PR TITLE
Update subiquity for /shutdown changes

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Dry-run installation didn't expose any problems apart from the /shutdown change: https://github.com/canonical/ubuntu-desktop-installer/pull/242

**Review by dbungert — APPROVED** [review]
I expect this should be no issue, but if people see subiquity not making installation progress, we'll want a copy of the subiquity-server-debug.log file.

**Comment by jpnurmi** [comment]
Is there something unfinished? Would you prefer to update subiquity later?

**Comment by dbungert** [comment]
No, I don't think so.
There was a rewrite of handling of what controllers are mapped to the client installer variants, so there is a nonzero chance that the install gets blocked waiting on a controller that is not going to be marked as configured.
You should know pretty quick by doing a test install.

**Comment by jpnurmi** [comment]
Ok. A dry-run installation went through fine. Let's merge this so we can give it a spin with the daily image tomorrow.

**Pull request merged**
