### PR TITLE
Add page indicator

### LINKED ISSUE #1348: We need some signifier of progress through the installer flow
image

Ubiquity included a number of dots to visualise to the user how far through the process they are. Whilst the dot approach is not necessary it would be more user friendly to have a visual presentation of progress through this UI even if not 100% accurate for all use-cases.

Windows 10 has 'chapter headings' throughout the flow to signify this as an alternative example 
image
image

@elioqoshi it might be good to experiment with mockups of a preferred presentation

### PR DESCRIPTION
**Pull request by d-loose**
[Screencast from 2023-02-21 15-30-17.webm](https://user-images.githubusercontent.com/113362648/220372982-2abb96b9-d8e5-4da6-bba6-915772c74b26.webm)

Depends on https://github.com/ubuntu-flutter-community/wizard_router/pull/30
Fixes #1348

### CODE REVIEW

**Comment by jpnurmi** [comment]
@elioqoshi, is the placement of the indicator ok?

**Comment by jpnurmi** [comment]
(the page indicator is not vertically center aligned with the back/continue buttons because there can be some status/info/warning labels on the left side)

image

**Comment by elioqoshi** [comment]
The indicators are a bit too big and too spaced out I'd say. I'd condense them a bit and if there is not a lot of space on the bottom, it could be placed on top of the vertical height of the buttons (end of the content area):

grafik

**Comment by jpnurmi** [comment]
Thanks! There should be 20px spacing between the buttons and the content on all pages so this could work. :+1:

**Comment by Feichtmeier** [comment]
#135

**Comment by jpnurmi** [comment]
> We purposely removed the indicators because it doesn't give you a good indication of where you are in the installation, as you could go to other pages during setup.

Ha, I thought it had been discussed before! :)

**Comment by elioqoshi** [comment]
@Feichtmeier Yeah, I assume we are contradicting our past decisions. In the past we had no Product Manager and this was a request we discussed with @local-optimum here as well, so I guess this is a revisited decision.

**Comment by Feichtmeier** [comment]
Np just wanted to link the issues together.

**Comment by d-loose** [comment]
How's this?

[Screencast from 2023-02-23 10-39-22.webm](https://user-images.githubusercontent.com/113362648/220870949-9a77eb9e-ed71-4d3b-938b-3e2130307d76.webm)

**Comment by d-loose** [comment]
Some improvements after following up on the discussion in the comments on the issue:

[Screencast from 2023-02-23 14-03-14.webm](https://user-images.githubusercontent.com/113362648/220914460-5caaafda-8748-4f51-af25-d453e42dbc42.webm)

**Comment by jpnurmi** [comment]
Could we move the battery warning changes to a separate PR, please? :)

**Comment by d-loose** [comment]
How closely do we want to follow the yaru style here?
I already added [customizable dot size and spacing to the page indicator widget](https://github.com/ubuntu/yaru_widgets.dart/pull/624), but this seems like a more drastic change.

**Comment by elioqoshi** [comment]
Ah I see what you mean. The color needs to be Ubuntu orange at least then. I don't think we should reivent this different from Yaru then for now.

**Comment by jpnurmi** [comment]
We could make YaruPageIndicator themeable so that it allows passing the box decoration via YaruPageIndicatorTheme. It was originally developed as an internal helper widget and only recently extracted from the carousel widget.

**Comment by d-loose** [comment]
> The color needs to be Ubuntu orange at least then. I don't think we should reivent this different from Yaru then for now.

It follows the theme's accent color (I'm using the red one here, but I should probably use the default in screenshots)


> We could make YaruPageIndicator themeable so that it allows passing the box decoration via YaruPageIndicatorTheme. It was originally developed as an internal helper widget and only recently extracted from the carousel widget.

Ah I see - I definitely support more `Yaru*Theme`s!

**Comment by elioqoshi** [comment]
> It follows the theme's accent color (I'm using the red one here, but I should probably use the default in screenshots)

Ah I see. Okay then. The accent color is too dark on the dark theme but that's another topic for a completely different thing.

**Comment by jpnurmi** [comment]
@elioqoshi should we move the release note label up, from the bottom bar to the content area?

image

image

**Comment by elioqoshi** [comment]
I think that makes sense.

btw, I will follow up to update this screen as discussed 2 weeks ago

**Review by jpnurmi — APPROVED** [review]
Right, we can tweak the only remaining footer label when we implement the new Try-or-install design.

LGTM :+1:

**Pull request merged**
