### PR TITLE
Set minimum width for wizard buttons

### PR DESCRIPTION
**Pull request by jpnurmi**
| Before | After |
|---|---|
| image | image |

Ref: #1467

### CODE REVIEW

**Comment by jpnurmi** [comment]
WIP: Depends on #1484 and #1485 to avoid conflicts.

**Comment by elioqoshi** [comment]
LGTM!

**Comment by jpnurmi** [comment]
Wait, 134 is not divisible by 8. :sweat_smile: Should it be 136 or does it matter?

**Review by elioqoshi — APPROVED** [review]
136 is fine, yep!

**Review by d-loose — APPROVED** [review]
:+1:

**Pull request merged**
