### PR TITLE
Installation complete: update logo

### PR DESCRIPTION
**Pull request by jpnurmi**
| Before | After |
|---|---|
| image | image |
| image | Screenshot from 2023-03-15 14-09-50 |

### CODE REVIEW

**Comment by jpnurmi** [comment]
@elioqoshi Should we have the same border around the logo on the new welcome page?

| Light | Dark |
|---|---|
| Screenshot from 2023-03-15 12-25-46 | Screenshot from 2023-03-15 12-25-19 |

**Comment by elioqoshi** [comment]
@jpnurmi we should!

btw, this is the mascot, not the logo, to be very specific

**Comment by jpnurmi** [comment]
The 8px wide border color is hardcoded to `#e5e5e5` :thinking: 

What if we used the "outline" color whatever comes from the theme?

| Light | Dark |
|---|---|
| image | image |

**Comment by jpnurmi** [comment]
Superseded by:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1637

**Pull request closed without merging**
