### PR TITLE
README: Update broken link and 22.04=>23.04

### PR DESCRIPTION
**Pull request by benjaoming**
Hi :wave: 

Fixing a broken link and adding a slightly more elaborated text.

I didn't like simply deleting the info about a 22.04 release without at least mentioning that there are reasons why it was postponed.

### CODE REVIEW

**Comment by benjaoming** [comment]
Oh a CLA, how great.

**Comment by benjaoming** [comment]
Now I agreed to the CLA, so you can re-run the action.

**Comment by jpnurmi** [comment]
Thanks for taking the time to write such a nice update and sorry for the trouble with the CLA check. Could you please add the same email address you use on GitHub to Launchpad so the bot will be able to recognize you, please?

```
Checking the following users on Launchpad:
- benjamin@overtag.dk ✕ (has no Launchpad account)
```

**Comment by benjaoming** [comment]
I used my GitHub username in the CLA.

Not gonna spend more time on this now, it's too much bureaucracy for too little.

**Comment by benjaoming** [comment]
I did sign the CLA, so you can still merge it if you want.

**Review by jpnurmi — APPROVED** [review]
LGTM :+1:

**Comment by benjaoming** [comment]
Awesome, thanks! I have a very hectic morning buraucracy-wise... the CLA was too much... but meeting a nice human being is the remedy for that :D

**Pull request merged**
