### PR TITLE
Updates and other software: explain disabled codecs with a tooltip

### PR DESCRIPTION
**Pull request by jpnurmi**
- The text was changed: "Install support for additional media formats" => "Download and install support for additional media formats"
- A "You are currently offline" tooltip is shown when hovering the disabled checkbox

| Light | Dark |
|---|---|
| image | image |

Close: #1390

### CODE REVIEW

**Comment by jpnurmi** [comment]
@elioqoshi Is this proposal ok?

**Comment by elioqoshi** [comment]
Structurally yes, but the tooltip is not accessible on light as orange lacks color contrast on white. It needs to be brownish in order to pass the contrast.

Also is this the standard tooltip we use? The shadow looks a bit weird

**Comment by jpnurmi** [comment]
Ok, hmm... the warning color comes from Yaru. Actually, do we need to change the text color or would it be enough to only use it for the warning icon?

This is not the standard Flutter tooltip because it can only contain text. It looked like this :(

Screenshot from 2023-02-15 08-01-37

**Comment by elioqoshi** [comment]
I think the standard tooltip looks fine as it's informational

**Comment by jpnurmi** [comment]
Ok, thanks! I've changed it to use the basic tooltip.

**Review by d-loose — APPROVED** [review]
:+1:

**Pull request merged**
