### PR TITLE
Support partially overridden flavor image assets

### PR DESCRIPTION
**Pull request by jpnurmi**
Before, a flavored installer had to bundle a full set of image assets.
This change makes it possible to override only specific assets and let
the app use the default assets for others.

### CODE REVIEW

**Comment by jpnurmi** [comment]
A dumb example that demonstrates how overriding a subset of image assets works. When there will be more image assets, flavors can choose which ones they want to override.

| Before | After |
|---|---|
| Screenshot from 2021-11-18 11-11-22 | Screenshot from 2021-11-18 11-10-29 |

**Comment by oSoMoN** [comment]
The OptionCard's title isn't visible any longer, as evidenced by your before/after screenshot (and I'm seeing this when testing locally, too).

**Comment by jpnurmi** [comment]
| Light | Dark | Flavor |
|---|---|---|
| Screenshot from 2021-12-15 08-27-29 | Screenshot from 2021-12-15 08-27-22 | Screenshot from 2021-12-15 08-28-29 |

**Comment by jpnurmi** [comment]
How could I not notice that...

**Review by oSoMoN — APPROVED** [review]
LGTM now, thanks!

**Pull request merged**
