### PR TITLE
Fix Active Directory controller name

### PR DESCRIPTION
**Pull request by dbungert**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Was it renamed? It said in the logs:

> to go {'ad'}

(20230306)

**Comment by jpnurmi** [comment]
Did it get mixed up?
```py
class ADController(SubiquityController):
    """ Implements the server part of the Active Directory feature. """
    model_name = "ad"
    endpoint = API.active_directory
```
https://github.com/canonical/subiquity/blob/cfeb3fe1638146e71ee98e185508ecf466645da7/subiquity/server/controllers/ad.py#L92-L95

**Comment by dbungert** [comment]
I appreciate and agree that the naming is inconsistent.  Allow me to restate my request to make the names consistent, @CarlosNihelton .

In today's ISO, it stops at the end with one controller to go.
If you `curl --unix-socket "/run/subiquity/socket" -X POST 'a/meta/mark_configured?endpoint_names=\["ad"\]'` , nothing will change.
If you `curl --unix-socket "/run/subiquity/socket" -X POST 'a/meta/mark_configured?endpoint_names=\["active_directory"\]' `, the install completes.

**Review by jpnurmi — APPROVED** [review]
ok, thanks for fixing it! 👍

**Comment by CarlosNihelton** [comment]
> I appreciate and agree that the naming is inconsistent.  Allow me to restate my request to make the names consistent, @CarlosNihelton .
> 
> In today's ISO, it stops at the end with one controller to go.
> If you `curl --unix-socket "/run/subiquity/socket" -X POST 'a/meta/mark_configured?endpoint_names=\["ad"\]'` , nothing will change.
> If you `curl --unix-socket "/run/subiquity/socket" -X POST 'a/meta/mark_configured?endpoint_names=\["active_directory"\]' `, the install completes.
> 

Looks like that blinded me! At least we will finish #1581 with no inconsistencies. Thanks for finding that one!

**Pull request merged**
