### PR TITLE
Project structure proposal

### PR DESCRIPTION
**Pull request by jpnurmi**
The proposal looks like this:
```
packages
├── subiquity_client
└── ubuntu_desktop_installer
    └── lib
        ├── app.dart
        ├── l10n
        ├── main.dart
        ├── pages
        |   └── foo_page.dart
        ├── routes.dart
        ├── widgets
        |   └── foo_view.dart
        └── widgets.dart
```
In the future, one would likely end up having typical `models/` and `services/` subdirectories too. Furthermore, more complex pages could also be organized into separate subdirectories once they start having view models and other page-specific files.

This change is partly motivated by #30 and would help to organize the files. :slightly_smiling_face:

P.S. `keyboard_model.dart` looks like a potential candidate for a small separate package so I left it in place for now.

### CODE REVIEW

**Comment by oSoMoN** [comment]
README.md also needs to be updated to reflect the new path to `subiquity_client`. This otherwise looks good to me.

**Comment by jpnurmi** [comment]
In the end, the structure is very much a matter of taste, of course, and the internets are full of various Flutter project structuring tips and opinions. :slightly_smiling_face: @ArishSultan, do you have any thoughts on this? This change would affect your ongoing tasks to some degree.

From what I've seen, the most common structures are either a) grouping by modules/features, or b) grouping by types (all services together, all repositories together, etc.). This proposal is sort of a mixture of the two in the sense that screens/pages would be independent modules that would not be aware of each other, but only known on the application level where the routes are defined and navigation is handled. And any data models and services that would be used across the modules would be grouped on the application level, whereas any module-specific models/services/repositories etc. would be inside the respective module.

**Comment by Feichtmeier** [comment]
Even if I haven't be asked: I think grouping by types makes sense if you have such things as model classes, service classes and view classes. The view dir could be further divided into pages where you really route with the navigator to and small views which are put into the widget tree via bottom navbar / rails.

**Comment by Feichtmeier** [comment]
Yeah :) we are on the same line. I didn't feel excluded, it was a bit humor, and I should improve at this field 👍 😆 
Breaking up the pages creates a lot diff, so it's understandable that you did not make this all at once

**Pull request merged**
