### PR TITLE
Loading screen

### PR DESCRIPTION
**Pull request by jpnurmi**
[Screencast from 2023-03-15 10-46-34.webm](https://user-images.githubusercontent.com/140617/225273404-940d2a84-7933-4272-aaf2-77c6af7b3b1d.webm)

### CODE REVIEW

**Comment by elioqoshi** [comment]
Squashing two flies at once here, updating the language selection screen to a dropdown instead and new alignment. Some subtle animations are also present to make this more enhanced.

https://user-images.githubusercontent.com/5436686/224757084-cd0eec8d-8fcb-43c1-8715-f6c13ce29ba1.mov

**Comment by elioqoshi** [comment]
I updated this screen includiong an updated dropdown for language selection as well as layout. Please mind the animations designed in such a way that the screens feel separate.

https://user-images.githubusercontent.com/5436686/224758597-9aa4d7c7-b977-45e3-bf02-da670c23c2ba.mov

**Comment by jpnurmi** [comment]
A small shortcut was taken with the transition because a slide transition would've needed structural changes to avoid sliding titles and buttons (we'd need to move the loading spinner inside the welcome screen instead of being two separate screens).

[Screencast from 2023-03-15 10-46-34.webm](https://user-images.githubusercontent.com/140617/225273404-940d2a84-7933-4272-aaf2-77c6af7b3b1d.webm)

**Review by d-loose — APPROVED** [review]
LGTM :+1:

**Pull request merged**
