### PR TITLE
Add basic theming & asset lookup capabilities for flavors

### PR DESCRIPTION
**Pull request by jpnurmi**
## Creating a flavor

- Create a new Flutter project
- Create symlinks (#477):
  - `<app>/subiquity` -> `/path/to/subiquity`
  - `<app>/test/socket` -> `/path/to/subiquity/.subiquity/socket`
- Add `ubuntu_desktop_installer` dependency (path) to `pubspec.yaml`
- Call `runInstallerApp()` and pass `FlavorData`

## Theming

```dart
import 'package:flutter/material.dart';
import 'package:ubuntu_desktop_installer/installer.dart';

void main(List<String> args) {
  runInstallerApp(
    args,
    flavor: FlavorData(
      name: 'Ubuntu X',
      theme: ThemeData(primarySwatch: Colors.purple),
    ),
  );
}
```

## Assets

Images can be replaced by placing them into `<app>/assets`. The default
assets in `ubuntu_desktop_installer` are used as fallbacks for missing
assets.

```yaml
flutter:
  assets:
    - assets/hard-drive.png
    - assets/repair-wrench.png
    - assets/steering-wheel.png
```

## Preview

Screenshot from 2021-11-08 09-24-10

P.S. By the time of taking the screenshot, the flavor name is not yet used in translations.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
We'll work out Yaru flavours on yaru.dart so you can take advantage of all the other changes than the orange and green accents

**Comment by oSoMoN** [comment]
LGTM, and works nicely.

**Comment by Feichtmeier** [comment]
If there is interest yaru.dart now comes with themes for standard ubuntu + 6 flavors:
https://github.com/ubuntu/yaru.dart/pull/110

You could use it for example like

```dart
import 'package:flutter/material.dart';
import 'package:ubuntu_desktop_installer/installer.dart';
import 'package:yaru/yaru.dart';

void main(List<String> args) {
  runInstallerApp(
    args,
    flavor: FlavorData(
      name: 'Ubuntu Mate',
      theme: yaruMateLight,
    ),
  );
}
```

I don't know if that function has a darkTheme property =)

**Comment by jpnurmi** [comment]
Yes, there's a `darkTheme` property too even if I had left it out from the simple example. :)

**Pull request merged**
