### PR TITLE
Build and expose WSL setup

### PR DESCRIPTION
**Pull request by didrocks**
As we won’t run as part of the snap, and we don’t have a full classic environment, build but don’t expose the binary in the snap.

Ship a script that mimic the desktop extension behaviour, we will have a script in the .deb package that mounts the needed snaps at the right place and ship it where it’s needed.

Ensure finally that the socket is passed to subiquity in dry-run, so that the latter creates the directory if not present.

This was tested and runs on WSL impish.

### CODE REVIEW

**Comment by didrocks** [comment]
Converting it as a draft as CI don’t pass. I think I understand the assumption of tests and CI about the socket argument, which is wrong IMHO as it prevents using the real system with it. Maybe it’s better to fix it beforehand on a separate branch.

**Comment by seb128** [comment]
The snapcraft ubuntu-wsl-setup parts is quite similar to the ubuntu-desktop-installer one, would it make sense perhaps to just have one so we don't do flutter channel/upgrade/config again? or are those calls basically a no-op if they have already been issued for another parts?

**Comment by didrocks** [comment]
This is not a no-op between the parts, but changing the channel/upgrade is not what is taking most of the time.

I don’t have strong opinion here, but this was to make the separation clearer. If you prefer one part, we can merge them.

**Comment by didrocks** [comment]
ok, so I withdraw latest commit for the socket change as the CI is heavily depending on it. The issue is that we can’t run (except if we create those symlinks…)  on a real system…

This needs to be fixed in a separate PR IMHO and adding also a socket argument to the desktop installer.

Ready for review then!

**Comment by seb128** [comment]
> This is not a no-op between the parts, but changing the channel/upgrade is not what is taking most of the time.
> 
> I don’t have strong opinion here, but this was to make the separation clearer. If you prefer one part, we can merge them.

Let's not delay the delay the merge on that, we can reshuffle later if needed. The snap is slow enough to build so it would be nice to not make it even longer if we can avoid, I will benchmark the alternative options and see what impacts it has and we can decide if we want to do a follow up tweak according to the results

**Review by seb128 — APPROVED** [review]
Let's merge, the launcher is non trivial but similar to what we already use

**Pull request merged**
