### PR TITLE
Update translation instructions

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
To be merged after ubuntu-wizard has been replaced by ubuntu-localizations in Weblate.

**Review by seb128 — CHANGES_REQUESTED** [review]
Thanks, as discussed by chat we are going to use a new project for those so the description is going to be need to be updated with the correct naming before landing

**Comment by jpnurmi** [comment]
The link is correct after all because we decided to keep ubuntu-localizations in the installer translation project.

**Review by seb128 — APPROVED** [review]
Right!

**Pull request merged**
