### PR TITLE
Allocate disk space improvements

### PR DESCRIPTION
**Pull request by jpnurmi**
- made data table scrollable
- indented partitions
- added a simple bar to visualize partitions

### CODE REVIEW

**Comment by jpnurmi** [comment]
| Before | After |
|---|---|
| allocate-disk-space-before | allocate-disk-space-after |

**Comment by jpnurmi** [comment]
By the way, is there's going to be a pre-defined set of partition colors? I made it go around the color wheel for now.

**Comment by oSoMoN** [comment]
> By the way, is there's going to be a pre-defined set of partition colors? I made it go around the color wheel for now.

That needs to be discussed with design (and the outcome documented). @long-chung ^

**Comment by oSoMoN** [comment]
This looks much better than the initial dummy implementation, thanks!

**Pull request merged**
