### PR TITLE
Correct spelling of Ethernet

### PR DESCRIPTION
**Pull request by robert-ancell**
Ethernet should use a capital letter.

### CODE REVIEW

**Review by seb128 — CHANGES_REQUESTED** [review]
The issue with patching translations is that it creates conflict in weblate which doesn't know how to handle the fact that its own records get different from what is in the vcs.

I've forced an export of the currently pending change from weblate, could we at least merge !1717 first and rebase to try to minimize the risk of conflict?

**Comment by jpnurmi** [comment]
Alternatively, we could only change `app_en.arb` and let Weblate warn translators about the case mismatch.

**Comment by seb128** [comment]
> Alternatively, we could only change `app_en.arb` and let Weblate warn translators about the case mismatch.

do you know how weblate and flutter handle that case? in a traditional gettext world the translations would be flagged as fuzzy and not be used anymore which would mean a visible regression for users until the translators go and revalidate the localized string

**Comment by jpnurmi** [comment]
I saw Weblate automatically proposing fixes to similar mismatches before so I thought it could take care of Ethernet vs. ethernet mismatches too but I'm probably wrong because I don't see any case mismatch on the list of translation checks. :(

https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Review by jpnurmi — APPROVED** [review]
LGTM :+1:

**Review by seb128 — APPROVED** [review]
thanks!

**Pull request merged**
