### PR TITLE
Who are you: generate user- and hostname when not specified

### PR DESCRIPTION
**Pull request by jpnurmi**
https://user-images.githubusercontent.com/140617/134480881-9fb8535b-ce82-44f6-b90f-822f85c442d3.mp4

Close: #338

### CODE REVIEW

**Comment by jpnurmi** [comment]
I'm not sure what happened with the recording. It's super sluggish but shows the behavior anyway...

**Comment by jpnurmi** [comment]
I'd have opened separate PRs, but to avoid a dependency chain of PRs, I hope it's ok to bundle the whole series of commits in the same PR to save time.

The commits are organized in logical steps so either rebasing or merging would be preferred to retain separate commits.

**Comment by oSoMoN** [comment]
When on the "Who are you?" page, if I press back and then continue again, I'm seeing the following exception:

    flutter: ERROR ubuntu_desktop_installer: Unhandled exception
	    StateError: Bad state: Stream has already been listened to.
    #0      _StreamController._subscribe (dart:async/stream_controller.dart:635:7)
    #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
    #2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
    #3      DBusSignalStream.listen (package:dbus/src/dbus_client.dart:128:31)
    #4      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
    #5      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
    #6      _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
    #7      HostnameService.init (package:ubuntu_desktop_installer/services/hostname_service.dart:35:51)
    <asynchronous suspension>
    #8      Future.wait.<anonymous closure> (dart:async/future.dart)
    <asynchronous suspension>

**Comment by oSoMoN** [comment]
As soon as I start typing in the name field, I'm seeing those two exceptions:

    flutter: ERROR ubuntu_desktop_installer: Unhandled exception
	    FlutterError: setState() or markNeedsBuild() called during build.
    This Form widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
    The widget on which setState() or markNeedsBuild() was called was:
      Form-[LabeledGlobalKey<FormState>#3d312]
    The widget which was currently being built when the offending call was made was:
      _UsernameFormField
    #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4305:11)
    #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4320:6)
    #2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
    #3      FormState._forceRebuild (package:flutter/src/widgets/form.dart:180:5)
    #4      FormState._fieldDidChange (package:flutter/src/widgets/form.dart:176:5)
    #5      FormFieldState.didChange (package:flutter/src/widgets/form.dart:496:23)
    #6      _TextFormFieldState.didChange (package:flutter/src/material/text_form_field.dart:395:11)
    #7      _TextFormFieldState._handleControllerChanged (package:flutter/src/material/text_form_field.dart:418:7)
    #8      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
    #9      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
    #10     TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:186:11)
    #11     TextEditingController.text= (package:flutter/src/widgets/editable_text.dart:171:5)
    #12     _ValidatedFormFieldState.didUpdateWidget (package:ubuntu_wizard/src/widgets/validated_form_field.dart:106:19)
    #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4855:57)
    #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
    #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
    #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
    #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
    #18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
    #19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
    #20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
    #21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
    #22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
    #23     _rootRun (dart:async/zone.dart:1428:13)
    #24     _CustomZone.run (dart:async/zone.dart:1328:19)
    #25     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
    #26     _invoke (dart:ui/hooks.dart:166:10)
    #27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
    #28     _drawFrame (dart:ui/hooks.dart:129:31)
    
    flutter: ERROR ubuntu_desktop_installer: Unhandled exception
	    FlutterError: setState() or markNeedsBuild() called during build.
    This Form widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
    The widget on which setState() or markNeedsBuild() was called was:
      Form-[LabeledGlobalKey<FormState>#3d312]
    The widget which was currently being built when the offending call was made was:
      _HostNameFormField
    #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4305:11)
    #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4320:6)
    #2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
    #3      FormState._forceRebuild (package:flutter/src/widgets/form.dart:180:5)
    #4      FormState._fieldDidChange (package:flutter/src/widgets/form.dart:176:5)
    #5      FormFieldState.didChange (package:flutter/src/widgets/form.dart:496:23)
    #6      _TextFormFieldState.didChange (package:flutter/src/material/text_form_field.dart:395:11)
    #7      _TextFormFieldState._handleControllerChanged (package:flutter/src/material/text_form_field.dart:418:7)
    #8      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
    #9      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
    #10     TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:186:11)
    #11     TextEditingController.text= (package:flutter/src/widgets/editable_text.dart:171:5)
    #12     _ValidatedFormFieldState.didUpdateWidget (package:ubuntu_wizard/src/widgets/validated_form_field.dart:106:19)
    #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4855:57)
    #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
    #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
    #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
    #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
    #18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
    #19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
    #20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
    #21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
    #22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
    #23     _rootRun (dart:async/zone.dart:1428:13)
    #24     _CustomZone.run (dart:async/zone.dart:1328:19)
    #25     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
    #26     _invoke (dart:ui/hooks.dart:166:10)
    #27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
    #28     _drawFrame (dart:ui/hooks.dart:129:31)

**Comment by oSoMoN** [comment]
That looks better, thanks!
One related functional problem: after filling in all text fields, including passwords, if I clear the hostname field, the "Continue" button remains enabled, allowing me to set an empty hostname.

**Comment by jpnurmi** [comment]
> One related functional problem: after filling in all text fields, including passwords, if I clear the hostname field, the "Continue" button remains enabled, allowing me to set an empty hostname.

Fixed, thanks!

**Comment by jpnurmi** [comment]
I had to sync the respective WSL page. I have added a note to share the logic: https://github.com/canonical/ubuntu-desktop-installer/issues/347#issuecomment-929887411

**Comment by oSoMoN** [comment]
LGTM, thanks!

**Pull request merged**
