### PR TITLE
Setup Melos for executing tasks across the project tree

### PR DESCRIPTION
**Pull request by jpnurmi**
Motivated by #77 - to avoid adding scripts around the project tree.

- Install [Melos](https://docs.page/invertase/melos):
  ```
  dart pub global activate melos
  ```

- Bootstrap the workspace:
  ```
  melos bootstrap
  ```

- Select a task interactively:
  ```
  melos run
  ```

- Run a specific task directly:
  ```
  melos run coverage
  ```

Currently, the following tasks are available:
1) analyze
2) coverage
3) format
4) generate
5) test

P.S. This is where the `packages/` subdirectory (https://github.com/canonical/ubuntu-desktop-installer/pull/68/commits/7e243de4bb422e44947e66c9b25f1d05987964b4) comes in handy. :slightly_smiling_face:

### CODE REVIEW

**Comment by jpnurmi** [comment]
Notice that this does _not_ make it anyhow mandatory to use Melos. It just makes certain tasks easier. At least, I have problems remembering commands like `run build_runner build --delete-conflicting-outputs`, which is why the [`codegen.sh`](https://github.com/canonical/ubuntu-desktop-installer/blob/main/packages/subiquity_client/tools/codegen.sh) script was included in an earlier PR. :smile:

However, #77 adds a couple of generated files to another package so I thought it would be nice to have all scripts/tasks in a central place. If one cannot remember the name of a specific task, `melos run` without a task name shows a nice list and lets one interactively select the desired task. :wink:

**Comment by oSoMoN** [comment]
That looks like a good idea.

When running `melos run generate` locally, I'm getting the following error:

    ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    subiquity_client:
    Could not find a file named "pubspec.yaml" in "/home/osomon/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-21.0.0".
    ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    $ melos exec
       └> dart run build_runner build --delete-conflicting-outputs
           └> FAILED (in 1 packages)
               └> subiquity_client (with exit code 255)

Any idea what's wrong with my setup?

**Comment by jpnurmi** [comment]
Ouch, those are nasty. Usually, I just try a random combination of `flutter clean`, `flutter/dart pub cache repair`, and then again `flutter pub get`. In the past, I have even deleted `.pub-cache` and started all over again. :smiley: Also, I have Dart SDK installed from https://dart.dev/get-dart#install-using-apt-get which I use to activate global packages so that they are unaffected when switching between different Flutter versions.

**Comment by oSoMoN** [comment]
Running `flutter clean` in `packages/subiquity_client/` did the trick, thanks.

**Pull request merged**
