### PR TITLE
Specify high contrast themes

### PR DESCRIPTION
**Pull request by jpnurmi**
Ref: #1570

### CODE REVIEW

**Comment by jpnurmi** [comment]
Yaru's high-contrast themes don't look correct anymore:
| Light | Dark |
|---|---|
| image | image |

- https://github.com/ubuntu/yaru.dart/pull/148

**Comment by jpnurmi** [comment]
I was mostly concerned about the dark background that has changed from black to "jet" but it's the same with GCC so perhaps it's fine after all?

image

**Comment by elioqoshi** [comment]
This seems okay to me. But for what's worth, there is a lot of things which are not great for high color contrast upstream in Yaru, but that's a separate thing.

**Comment by jpnurmi** [comment]
We'll fix the high-contrast themes in yaru.dart. Some relevant tickets:
- https://github.com/ubuntu/yaru.dart/issues/305
- https://github.com/ubuntu/yaru.dart/issues/302

**Review by d-loose — APPROVED** [review]
:+1:

**Pull request merged**
