### PR TITLE
Warn when on battery

### PR DESCRIPTION
**Pull request by jpnurmi**
Screenshot from 2021-12-06 14-04-54

Fixes: #526

### CODE REVIEW

**Comment by jpnurmi** [comment]
Depends on https://github.com/canonical/upower.dart/pull/18

**Comment by jpnurmi** [comment]
Note to self: sync PropertyStreamNotifier with https://github.com/canonical/ubuntu-desktop-installer/pull/600

**Comment by oSoMoN** [comment]
There are now two copies of `property_stream_notifier.dart`:

    ./packages/ubuntu_wizard/lib/src/utils/property_stream_notifier.dart
    ./packages/ubuntu_desktop_installer/lib/pages/connect_to_internet/property_stream_notifier.dart

**Comment by jpnurmi** [comment]
And they have already deviated too. :smile: I have a note to sync with #600 before merging.

**Review by oSoMoN — APPROVED** [review]
Other than the `PropertyStreamNotifier` duplication, this looks good to me, and works as advertised (tested on a laptop).

**Pull request merged**
