### PR TITLE
CI: add check for outdated generated localizations files

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
I was hesitant to add this before because Flutter stable and dev/master produced slightly differently formatted files. This is no longer the case after the latest stable 2.5 release.

**Comment by seb128** [comment]
Thanks for the work, one question, why did we have a git clean and why isn't that needed anymore?

**Comment by jpnurmi** [comment]
Sorry for trying to slip in changes that are on the borderline of being unrelated. :) Cleaning the repo was a workaround for the problem that got fixed by https://github.com/canonical/ubuntu-desktop-installer/pull/274

**Review by seb128 — APPROVED** [review]
Alright, ideally those would be different commits in the same PR at least so it's easier to understand the change when reading history but it's minor enough that we should be able to deal with having the explanation here if someone really wants to figure out the why :-)

**Comment by jpnurmi** [comment]
True! I've split the commits, to leave a clear track.

**Comment by seb128** [comment]
Thanks! Feel free to merge, I'm unsure why the codecov/project check is read but it shows changes in dart files so it doesn't much sense there?

**Comment by jpnurmi** [comment]
Looks a lot like something that was merged earlier today. Rebasing would help but I'm not going to bother in this case. :)

**Pull request merged**
