### PR TITLE
Added const before sizedbox

### PR DESCRIPTION
**Pull request by Abhishek01039**
flutter skips rebuilding the const widgets. If we use const the widget only builds once. It doesn't rebuild when the build method reruns when you call setState.

### CODE REVIEW

**Comment by MarcusTomlinson** [comment]
@Abhishek01039, thanks for the contribution!

Could you please sign our CLA: https://ubuntu.com/legal/contributors/agreement

**Comment by Abhishek01039** [comment]
Done @MarcusTomlinson

**Comment by MarcusTomlinson** [comment]
@Abhishek01039 fyi: https://github.com/canonical/ubuntu-desktop-installer/pull/17/checks?check_run_id=1837968409

**Comment by Abhishek01039** [comment]
But I have done that even twice time.

**Comment by MarcusTomlinson** [comment]
> But I have done that even twice time. @MarcusTomlinson

It appears you require a https://launchpad.net account under the email abhishekghaskata1999@gmail.com.

**Comment by Abhishek01039** [comment]
> > But I have done that even twice time. @MarcusTomlinson
> 
> It appears you require a https://launchpad.net account under the email [abhishekghaskata1999@gmail.com](mailto:abhishekghaskata1999@gmail.com).

Done ✅

**Comment by MarcusTomlinson** [comment]
> > > But I have done that even twice time. @MarcusTomlinson
> > 
> > 
> > It appears you require a https://launchpad.net account under the email [abhishekghaskata1999@gmail.com](mailto:abhishekghaskata1999@gmail.com).
> 
> Done ✅

Don't see you: https://launchpad.net/+search?field.text=abhishekghaskata1999%40gmail.com&field.actions.search=Search

**Comment by Abhishek01039** [comment]
image

**Comment by Abhishek01039** [comment]
I have verified the account also! @MarcusTomlinson

**Comment by MarcusTomlinson** [comment]
Can you log into https://launchpad.net using your Ubuntu One credentials.

**Comment by Abhishek01039** [comment]
image

**Comment by Abhishek01039** [comment]
https://launchpad.net/~abhishek01039 
See this @MarcusTomlinson

**Comment by MarcusTomlinson** [comment]
> https://launchpad.net/~abhishek01039
> See this @MarcusTomlinson

Ok cool now you have a LP account.

Now we're getting `abhishekghaskata1999@gmail.com (https://api.launchpad.net/1.0/~abhishek01039) has NOT signed the CLA`

**Comment by MarcusTomlinson** [comment]
> what should I give here
> `Please add the Canonical Project Manager or contact`?

You can put my details there.

**Comment by Abhishek01039** [comment]
image

**Comment by Abhishek01039** [comment]
What could be the problem here?

**Comment by Abhishek01039** [comment]
What could be the problem here?
like any mismatch details which I gave or something

**Comment by MarcusTomlinson** [comment]
> What could be the problem here?
> like any mismatch details which I gave or something

I _think_ it may have something to do with the fact that there are no emails listed under **Email:** on your account page: https://launchpad.net/~abhishek01039

Could you click "Change email settings" under that heading and add abhishekghaskata1999@gmail.com.

**Comment by Abhishek01039** [comment]
```set as contact address``` @MarcusTomlinson

**Comment by MarcusTomlinson** [comment]
> `set as contact address` @MarcusTomlinson

So sorry about all this! I suspect our CLA check process in CI is broken. I'll look into this today and revert.

**Comment by MarcusTomlinson** [comment]
@Abhishek01039 so the issue here is that we've only recently opened CLA signing to GitHub users, while our `cla-check` script is verifying against Launchpad only.

I've contacted Legal and they've confirmed that you have signed the agreement, so I can go ahead and merge this now.

We'll try to get this fixed ASAP. So sorry for the confusion, and welcome to the contributors list!

**Pull request merged**
