### PR TITLE
subiquity: add a basic integration test

### PR DESCRIPTION
**Pull request by dbungert**
The version of curtin and probert expected by a given version of
subiquity should match the actual version in use for
ubuntu-desktop-installer.

### CODE REVIEW

**Comment by dbungert** [comment]
Previous check run correctly showing this test failing: https://github.com/canonical/ubuntu-desktop-installer/runs/3590339107?check_suite_focus=true

**Comment by jpnurmi** [comment]
Could we place the script in `.github/scripts`?

**Review by jpnurmi — APPROVED** [review]
Thanks, LGTM :+1:

**Comment by seb128** [comment]
How is that working? Does it mean that when we update subiquity we need to also think about updating our snapcraft to use a matching curtin version? If so maybe it would make to add a script 'update-subiquity' which does that for us? (the check is still useful to have but the less manual work the better right?)

**Comment by jpnurmi** [comment]
Would it be ok to have a bot that creates a PR to auto-roll the submodule nightly or weekly?

**Comment by jpnurmi** [comment]
Something similar to what Flutter does for the engine and plugins:
https://github.com/flutter/flutter/pulls?q=is%3Apr+is%3Aclosed+roll

**Comment by seb128** [comment]
I guess it depends of our strategy, do we want to follow subiquity closely and update often, in which case the auto PR makes sense,  or do we want to avoid changes when not needed and only pull an update when it has been a while or if there is a reason to do so?

**Comment by jpnurmi** [comment]
Yeah. It could help to catch issues early, at least. Oh, and the PRs would not be auto-merged, of course.

On a related note, I have also prepared an integration test that goes through the entire installation wizard for an extra safety net: https://github.com/canonical/ubuntu-desktop-installer/pull/283

**Comment by dbungert** [comment]
I wanted to explicitly say that the version of curtin that subiquity expects was the version that we were using by default for u-d-i.

Yes, a script to automate updating the snapcraft.yaml for u-d-i sounds like a good addition, I can put that together.
The test is still valuable because someone might manually adjust the snapcraft.yaml.

**Comment by dbungert** [comment]
#312

**Pull request merged**
