### PR TITLE
Use disk model and vendor names from subiquity 

### PR DESCRIPTION
**Pull request by jpnurmi**
Disk model and vendor names were added in canonical/subiquity#1138. It's no longer necessary to lookup libudev through FFI, and as a bonus, the names match the machine config in dry-run mode.

Close: #415

### CODE REVIEW

**Comment by jpnurmi** [comment]
For example, a dry-run with the default simple.json:

| Before, /dev/sda not mounted | Before, /dev/sda mounted | After, /dev/sda from simple.json |
|---|---|---|
| Screenshot from 2021-12-15 10-05-47 | Screenshot from 2021-12-15 10-23-43 | Screenshot from 2021-12-15 10-05-10 |

**Review by robert-ancell — APPROVED** [review]
Yay! That looks much tidier :)

**Comment by jpnurmi** [comment]
Hmm, I wish we could get the same information for network devices from NetworkManager. Then we could get rid of the libudev FFI bindings altogether.

There's nm_device_get_product() and nm_device_get_vendor() in libnm but no corresponding properties in the D-Bus API.

**Comment by robert-ancell** [comment]
> Hmm, I wish we could get the same information for network devices from NetworkManager. Then we could get rid of the libudev FFI bindings altogether.
> 
> There's nm_device_get_product() and nm_device_get_vendor() in libnm but no corresponding properties in the D-Bus API.

If that's information that NetworkManager consumers are likely to use then we probably should add helpers like that to nm.dart.

**Pull request merged**
