### PR TITLE
Drop repetitive and long FS descriptions in favor of short names

### PR DESCRIPTION
**Pull request by jpnurmi**
Just updating the English translation which is used as a template for all others. The bot will automatically regenerate the untranslated entries and open a PR. For already translated entries, Weblate will show a warning that they are out of date.

```
$ apt show btrfs-progs 2>/dev/null | grep Desc
Description: Checksumming Copy on Write Filesystem utilities
```

Screenshot from 2023-03-01 18-41-44

Close: #1294

### CODE REVIEW

**Comment by jpnurmi** [comment]
My personal favorite is the Subiquity way :)

image

@elioqoshi Do you have any thoughts on this? IMO the long descriptions make it almost harder to find what you're looking for. There's so much text that it takes (unnecessary?) extra time to scan through the content.

image

**Comment by elioqoshi** [comment]
@jpnurmi could you elaborate what I should be looking at in comparison? I am not sure what the impact is here.

**Comment by jpnurmi** [comment]
@elioqoshi Here's the current version which already looks somewhat heavy with pretty long descriptions, a proposal that makes the Btrfs description even longer, and a counter-proposal that drops all those descriptions to make it look like Subiquity. :) Yet another option could be to move the description to a second line with a smaller font and weaker color so it becomes less prominent and eats up less space...

| Current | Proposal | Alternative | Yet another |
|---|---|---|---|
| image | image | image | image |

**Comment by elioqoshi** [comment]
Ah yeah, I think the Subiquity way is better, with no descriptions. Descriptions won't help users who don't know what they are doing anyway and users who know what they are looking for have no use for it. So the alternative proposal looks best to me I think

**Comment by jpnurmi** [comment]
Getting back to this while we still can... should we go with the short names?

image

**Review by xnox — APPROVED** [review]

**Pull request merged**
