### PR TITLE
Updated Subiquity to the latest and greatest

### PR DESCRIPTION
**Pull request by CarlosNihelton**
Hello, @jpnurmi !

Per our conversation earlier, we would like to have the next cloud image built with the latest revision of Subiquity, for further testing with WSL.

The proposed update was made with the help of the `update-subiquity` script. The changes generated by the script on the `snapcraft.yaml` file consisted of only space removals and one replacement of double quotes by single quotes, so I didn't include that in this pull request.

### CODE REVIEW

**Comment by jpnurmi** [comment]
Sorry for the unrelated formatting changes in `pubspec.yaml`. The script is new and apparently, nobody bothered to commit those minor formatting changes introduced by Python YAML library... :)

**Comment by jpnurmi** [comment]
Dry-install doesn't work with the latest subiquity. Perhaps this warning is related:
```
/home/jpnurmi/Projects/canonical/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/server/controllers/mirror.py:115: RuntimeWarning: coroutine 'AptConfigurer.cleanup' was never awaited
  self.apt_configurer.cleanup()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by CarlosNihelton** [comment]
> Dry-install doesn't work with the latest subiquity. Perhaps this warning is related:
> 
> ```
> /home/jpnurmi/Projects/canonical/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/server/controllers/mirror.py:115: RuntimeWarning: coroutine 'AptConfigurer.cleanup' was never awaited
>   self.apt_configurer.cleanup()
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> ```

Fixing the warning didn't solve the issue. Need to dig into it a little further. Sorry about that.

**Comment by jpnurmi** [comment]
No worries, I can help to bisect. I got distracted by some other issues. 😆

**Review by jpnurmi — APPROVED** [review]
Thanks, LGTM! :+1:

**Comment by CarlosNihelton** [comment]
The addition of the `ubuntu_advantage` controller in Subiquity was not handled in the UI code. That's why. We should be fine for now. Just pushed a small commit to add it to the list of controllers marked configured on wizard startup. Thanks for the guidance.

**Pull request merged**
