### PR TITLE
Turn off the public_member_api_docs linter rule

### PR DESCRIPTION
**Pull request by jpnurmi**
First of all, this linter rule is so noisy that it hides useful linter
issues. There are  linter issues slipping in due to `--no-fatal-infos`,
which is used in the CI to ignore `public_member_api_docs`.

Secondly, in an app project where there tend to be areas that don't need
docs, this linter rule results in not-so-useful docs that basically
repeat the same what the member name states, just to silence the linter
without adding any real value. For example:

    /// Does something.
    void doSomething() { ... }

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I appreciate this change. Currently the warnings are flooding the workspace and one is distracted by actually new warnings maybe created by yourself or just new ones in general that should be removed fast. :)

**Comment by CarlosNihelton** [comment]
Endorsed. More important warnings are being shadowed out by this `public_member_api_docs` rule and the `effective_dart` depracation notice recommends `package:lints` for Dart-only and `package:flutter_lints` which extends the previous for Flutter, with up-to-date rules.

**Review by robert-ancell — APPROVED** [review]
LGTM

**Comment by jpnurmi** [comment]
Instead of switching to `flutter_lints` in the same PR, I have reduced the scope of this PR to turn off `public_member_api_docs` and nothing else.

**Comment by oSoMoN** [comment]
LGTM, thanks!

**Comment by jpnurmi** [comment]
Thanks!

**Pull request merged**
