### PR TITLE
Create/edit partition: use MenuButtonBuilder for FS type

### PR DESCRIPTION
**Pull request by jpnurmi**
## Before

[Screencast from 2023-03-09 10-48-26.webm](https://user-images.githubusercontent.com/140617/223985539-5ac03860-b1cb-4f72-9d26-7496dad1a687.webm)

## After

[Screencast from 2023-03-09 10-49-17.webm](https://user-images.githubusercontent.com/140617/223985569-0ed40490-c197-4b92-99a0-f316295183d8.webm)

Ref: #1563

### CODE REVIEW

**Comment by jpnurmi** [comment]
@d-loose sorry for bugging but did this get buried in the notification spam? :woozy_face:

**Comment by d-loose** [comment]
Oh yes, sorry!
All those PRs look the same :D

**Review by d-loose — APPROVED** [review]
:+1:

**Comment by jpnurmi** [comment]
Thanks! I could've pushed these in one go but it felt more convenient this way to avoid updating tests all over the place at once... :)

**Pull request merged**
