### PR TITLE
Add helper package for determining password quality

### PR DESCRIPTION
**Pull request by jpnurmi**
This allows us to implement a proper password quality checking similarly to gnome-control-center: https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/user-accounts/pw-utils.c#L137

Needed for #40 (Who are you) and #156 (WSL Profile setup).

### CODE REVIEW

**Comment by jpnurmi** [comment]
@robert-ancell What do you think, would it be worth it to port https://github.com/libpwquality/libpwquality to Dart?

**Comment by jpnurmi** [comment]
Another option: https://pub.dev/packages/password_strength

**Review by robert-ancell — APPROVED** [review]
This looks like a reasonable strategy to me - I don't think we want to go down the path of implementing the libpwquality logic in Dart as this would be a security risk and we could diverge from the gnome-control-center behaviour.

In the future we could consider the password_strength package or writing our own, but it doesn't seem worth it at this point.

**Comment by jpnurmi** [comment]
An alternative based on [password_strength](https://pub.dev/packages/password_strength): https://github.com/canonical/ubuntu-desktop-installer/pull/186

**Pull request closed without merging**
