### PR TITLE
Let subiquity decide the keyboard layout and variant

### PR DESCRIPTION
**Pull request by jpnurmi**
Throw out the keyboard_info package that detects the DE's currently
selected keyboard layout. Let subiquity make the call which layout and
variant is the best match for the language/locale selected on the first
page.

Related issues:
- #388
- #163

### CODE REVIEW

**Comment by jpnurmi** [comment]
For me, this doesn't change the behavior in the sense that my system keyboard layout is still pre-selected regardless of the language selection.

The rest needs to be done in subiquity so that `POST /locale` followed by `GET /keyboard` answers with a keyboard layout matching the language/locale.

**Review by oSoMoN — APPROVED** [review]
Sorry for taking so long to review this. There are a couple of minor merge conflicts to resolve, but it otherwise looks good to me, and I tested locally that this works as expected.

**Comment by oSoMoN** [comment]
I am pretty sure that when I tested and approved this PR, the behaviour was as expected (i.e. unchanged), but I'm now consistently seeing the US English keyboard layout being selected by default on my system where the default locale is `fr_FR.UTF-8` and my default keyboard layout is `fr-bépo`. I bissected, and sure enough this change is causing the regression.
I wonder what's going on?

**Comment by oSoMoN** [comment]
And here are the logs that demonstrate the problem:

    flutter: INFO welcome: Set fr_FR as system locale
    flutter: DEBUG subiquity_client: POST http://localhost/locale
    flutter: DEBUG subiquity_client: ==> setLocale("fr_FR.UTF-8") null
    flutter: DEBUG subiquity_client: GET http://localhost/keyboard
    flutter: DEBUG subiquity_client: ==> keyboard() {"setting": {"layout": "us", "variant": "", "toggle": null}, "layouts": [{"code": "af", "name": "Afghan", "variants": [{...
    flutter: INFO keyboard_layout: Loaded 99 keyboard layouts

It looks like subiquity isn't selecting the correct layout based on the selected locale.

**Comment by jpnurmi** [comment]
I'm not sure how subiquity determines that, but somehow it's correctly able to detect 'fi' for me even when I select French.
```
flutter: INFO welcome: Selected fr_FR as UI language
flutter: INFO welcome: Set fr_FR as system locale
flutter: DEBUG subiquity_client: POST http://localhost/locale
flutter: DEBUG subiquity_client: GET http://localhost/keyboard
flutter: DEBUG subiquity_client: ==> setLocale("fr_FR.UTF-8") null
flutter: DEBUG subiquity_client: ==> keyboard() {"setting": {"layout": "fi", "variant": "", "toggle": null}, "layouts": [{"code": "af", "name": "Afghan", "variants": [{...
flutter: INFO keyboard_layout: Loaded 99 keyboard layouts
```

**Comment by jpnurmi** [comment]
It happened to me too while showing the app to the QA team. I noticed I had some ghost subiquity instances in the background so I'm wondering if it could be somehow related to that.

**Comment by oSoMoN** [comment]
I just tested again, making sure that there were no subiquity running before, and I'm still consisently seeing the incorrect keyboard layout being selected.

**Comment by oSoMoN** [comment]
And this appears to be [a known bug](https://bugs.launchpad.net/subiquity/+bug/1767054) in subiquity.

**Pull request merged**
