### PR TITLE
CI: check outdated generated files

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by oSoMoN** [comment]
The CI failure is raising an interesting question: mocks will differ sligthly if they were generated with a different minor version of mockito. How do we deal with that?

**Comment by jpnurmi** [comment]
I believe `pubspec.lock` is supposed to address the problem by pinning dependencies to certain versions, but it never worked too well when jumping between various Flutter versions. Perhaps we should restrict all generator package versions (i.e. remove the hat) in `pubspec.yaml`?

**Comment by oSoMoN** [comment]
I guess that would work, yes.

**Comment by oSoMoN** [comment]
LGTM, thanks!

**Pull request merged**
