### PR TITLE
Add Subiquity endpoints and data classes for WSL configs

### PR DESCRIPTION
**Pull request by jpnurmi**
/cc @patrick330602

### CODE REVIEW

**Comment by jpnurmi** [comment]
For the time being, this requires the [WSL feature branch](https://github.com/ubuntu/subiquity/tree/wsl/main) of Subiquity.

**Comment by jpnurmi** [comment]
Notes:
- The WSL tests are in the same `subiquity_client_test.dart` file because `flutter test` runs multiple parallel test jobs by default. If the tests were in different files, they would fail unless the `-j1` command-line argument was passed.
- The test file diff looks exhausting but most of it is indentation changes for grouping the existing tests. The two groups have a different setup for the server.

**Comment by jpnurmi** [comment]
I have removed all server changes etc. and left the endpoints and data classes only. This is enough for being able to run mocked tests for WSL pages and models.

**Comment by jpnurmi** [comment]
Ha, I got caught right away 😁

**Comment by oSoMoN** [comment]
I cannot comment on the various fields of the configuration data structures, but the change otherwise looks sound.

**Pull request merged**
