### PR TITLE
Try or install redesign

### PR DESCRIPTION
**Pull request by jpnurmi**
# Without repair (current)

| Before | After |
|---|---|
| image | image |
| image | image |
| image | image |
| image | image |

# With repair (future)

| Before | After |
|---|---|
| image | image |

Close: #1482

### CODE REVIEW

**Comment by d-loose** [comment]
Some parts of the text can be cut off on very small window sizes (close to 800x600) - is this already solved by switching to full-screen?

[Screencast from 2023-03-02 16-54-16.webm](https://user-images.githubusercontent.com/113362648/222481224-3755a640-fea5-4de0-9b08-8ef287f7b7b7.webm)

**Comment by jpnurmi** [comment]
The new design works much better in 800x600 :)

image

**Comment by d-loose** [comment]
Oh wow, this was before the afternoon coffee - I didn't realize I was checking the old design :D

**Review by d-loose — APPROVED** [review]
LGTM :+1:

**Comment by elioqoshi** [comment]
This is looking gorgeous, thanks so much for that, really looking forward to see this in action :)

The logos between light and dark are however not exactly the same size and position. Is that something you fixed already after our discussion? Apart that it looks good to go

**Review by elioqoshi — APPROVED** [review]

**Comment by jpnurmi** [comment]
Right, I synced the logos after taking the screenshots. Here's a proof :)

[Screencast from 2023-03-03 10-54-28.webm](https://user-images.githubusercontent.com/140617/222689568-4d5494d4-0f28-44a2-a669-30b002472b6c.webm)

**Pull request merged**
