### PR TITLE
Skip the CLA check for pull requests opened by Weblate (translations).

### PR DESCRIPTION
**Pull request by oSoMoN**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Thanks! Can we allow the [renovate](https://github.com/canonical/ubuntu-desktop-installer/pull/1155) bot too?

**Review by jpnurmi — APPROVED** [review]
Ooh, I never realized Weblate wasn't a bot but temporarily dumping the context sounds good! There's actually one flutter_html update in the queue that we don't want but can use for testing.

**Comment by oSoMoN** [comment]
Done: 6fcc7790c6e78b692e40d77fc833a79f629d30a6, I'll revert and add the right condition for renovate.

**Comment by oSoMoN** [comment]
There: #1186

**Pull request merged**
