### PR TITLE
Close the window after a reboot request

### PR DESCRIPTION
**Pull request by jpnurmi**
Ref: #224

### CODE REVIEW

**Comment by mwhudson** [comment]
It's safe to call the reboot endpoint in dry run mode, it just causes the server to exit.

**Comment by mwhudson** [comment]
In fact in general the client should not have to care about dry-run at all -- the tui client barely does (it affects how crash reports are generated and enables some dry-run only keybindings).

**Comment by jpnurmi** [comment]
With these changes the request is sent, but `RebootController.POST` gets stuck at [`await self.rebooting_event.wait()`](https://github.com/canonical/subiquity/blob/main/subiquity/server/controllers/reboot.py#L44) and `RebootController.reboot()` never gets called. What could be the problem?

**Comment by jpnurmi** [comment]
Reboot works after installation when the app status is done, but not from the `Turn off RST` or `Turn off BitLocker` screens.

**Comment by mwhudson** [comment]
Oh yeah that makes some kind of sense, the reboot controller waits for the installation to complete before actually restarting. We should add a parameter for this -- "immediate" or something I guess?

**Review by robert-ancell — APPROVED** [review]
LGTM

**Comment by jpnurmi** [comment]
> We should add a parameter for this -- "immediate" or something I guess?

Sounds good :+1:

**Pull request merged**
