### PR TITLE
Remove unsupported .arb file

### PR DESCRIPTION
**Pull request by jpnurmi**
There are .arb files prepared for all supported languages, but _Start new translation_ was still enabled in Weblate and thus, an unsupported language file slipped in in #519.

### CODE REVIEW

**Review by seb128 — APPROVED** [review]
Thanks, the UI for create new languages has been disabled now

**Comment by jpnurmi** [comment]
Thanks, the build is back to green.

**Comment by SelyanKab** [comment]
Hello,
I am the translator of kabyle locale in Ubuntu Intsller project in Weblate, I wounder why Kabyle is not yet supported in the installer, the localization oh Ubuntu is still runing in Launchpad.

**Comment by jpnurmi** [comment]
Hi @SelyanKab, my apologies for not leaving more details here. 

In short, the problem is that we got a build failure because Flutter does not support languages with 3-letter codes such as Kabyle (kab): https://github.com/flutter/flutter/issues/92818. The issue is already being worked on, though, so there's a good chance that we might be able to support more languages in the near future.

**Comment by SelyanKab** [comment]
Hi @jpnurmi , Thank you for explaining that, I hope the issue will be fixed soon.
We are going to continue the traduction in Weblate.
thank you.

**Pull request merged**
