### PR TITLE
Redesigned installation slides

### PR DESCRIPTION
**Pull request by jpnurmi**
## Light

[installation-slides-light.webm](https://user-images.githubusercontent.com/140617/224557290-9bada3c8-497d-4692-85de-8a46cb473fad.webm)

## Dark

[installation-slides-dark.webm](https://user-images.githubusercontent.com/140617/224557279-4709860a-d47f-4c11-8686-118500dd02d7.webm)

### CODE REVIEW

**Comment by jpnurmi** [comment]
@elioqoshi we need the new mascot for the first slide :)

**Review by d-loose — APPROVED** [review]
> P.S. I still need to double-check that all screenshots and image assets look fine on a high-DPI display but implementation-wise this is ready for review. :)

Some screenshots are blurry at least when viewed at full screen (1920x1080)

Implementation-wise: LGTM :+1:

**Comment by jpnurmi** [comment]
Normally, the window size is fixed to 960x680. It may end up being a bit smaller (we have promised to support down to 800x600 screens) or even slightly larger when shown full screen because for example a 1024x768 screen doesn't have enough space to show a 960x680 window after deducting the dock size etc.

**Comment by jpnurmi** [comment]
Alrighty, let's merge this! We'll fine-tune the screenshots separately case by case.

**Pull request merged**
