### PR TITLE
subiquity,curtin,probert: bitlocker/raid fixes

### PR DESCRIPTION
**Pull request by dbungert**

### CODE REVIEW

**Comment by dbungert** [comment]
Adds info like this:
```
{
  "disks": [
    {
      "partitions": [
        {
          "size": 85240896512,
          "number": 3,
          "annotations": [
            "existing",
            "already formatted as BitLocker",
            "not mounted"
          ]
        }
      ]
    }
  ]
}
```

**Comment by dbungert** [comment]
Correct.

**Comment by oSoMoN** [comment]
I updated my copy of main with that new subiquity checkout, and am testing in dry run mode with `examples/existing-partitions.json`. When clicking "Start Installation" on the "Allocate disk space" page, I'm getting a dart exception:

    flutter: Storage config: [
      {
        "ptable": "gpt",
        "serial": "serial1",
        "path": "/dev/vdb",
        "wipe": "superblock-recursive",
        "preserve": false,
        "name": "",
        "grub_device": false,
        "type": "disk",
        "id": "disk-vdb"
      },
      {
        "ptable": "gpt",
        "serial": "serial2",
        "path": "/dev/vdc",
        "preserve": true,
        "name": "",
        "grub_device": false,
        "type": "disk",
        "id": "disk-vdc"
      },
      {
        "ptable": "gpt",
        "serial": "serial3",
        "path": "/dev/vdd",
        "preserve": true,
        "name": "",
        "grub_device": false,
        "type": "disk",
        "id": "disk-vdd"
      },
      {
        "ptable": "gpt",
        "serial": "serial4",
        "path": "/dev/vde",
        "preserve": true,
        "name": "",
        "grub_device": false,
        "type": "disk",
        "id": "disk-vde"
      },
      {
        "device": "disk-vdc",
        "size": 10735321600,
        "flag": "linux",
        "number": 1,
        "preserve": true,
        "grub_device": false,
        "type": "partition",
        "id": "partition-vdc1"
      },
      {
        "device": "disk-vdd",
        "size": 10735321600,
        "flag": "linux",
        "number": 1,
        "preserve": true,
        "grub_device": false,
        "type": "partition",
        "id": "partition-vdd1"
      },
      {
        "device": "disk-vde",
        "size": 10735321600,
        "flag": "linux",
        "number": 1,
        "preserve": true,
        "grub_device": false,
        "type": "partition",
        "id": "partition-vde1"
      },
      {
        "name": "amazing-vg",
        "devices": [
          "partition-vde1"
        ],
        "preserve": true,
        "type": "lvm_volgroup",
        "id": "lvm-volgroup-amazing-vg"
      },
      {
        "name": "my-lv1",
        "volgroup": "lvm-volgroup-amazing-vg",
        "size": "5364514816B",
        "preserve": true,
        "type": "lvm_partition",
        "id": "lvm-partition-my-lv1"
      },
      {
        "fstype": "ext4",
        "volume": "lvm-partition-my-lv1",
        "uuid": "6a13a61c-51d5-46b8-bb97-02341f79e003",
        "preserve": true,
        "type": "format",
        "id": "format-lvm-partition-my-lv1"
      },
      {
        "name": "md127",
        "raidlevel": "raid1",
        "devices": [
          "partition-vdc1",
          "partition-vdd1"
        ],
        "spare_devices": [],
        "preserve": true,
        "type": "raid",
        "id": "raid-md127"
      },
      {
        "fstype": "ext4",
        "volume": "raid-md127",
        "uuid": "f59e9a4e-2ffd-4746-8f3c-1a6fd3556ba4",
        "preserve": true,
        "type": "format",
        "id": "format-raid-md127"
      },
      {
        "device": "disk-vdb",
        "size": 536870912,
        "wipe": "superblock",
        "flag": "boot",
        "number": 1,
        "preserve": false,
        "grub_device": true,
        "type": "partition",
        "id": "partition-0"
      },
      {
        "fstype": "fat32",
        "volume": "partition-0",
        "preserve": false,
        "type": "format",
        "id": "format-1"
      },
      {
        "device": "disk-vdb",
        "size": 10198450176,
        "wipe": "superblock",
        "flag": "",
        "number": 2,
        "preserve": false,
        "type": "partition",
        "id": "partition-1"
      },
      {
        "fstype": "ext4",
        "volume": "partition-1",
        "preserve": false,
        "type": "format",
        "id": "format-2"
      },
      {
        "path": "/",
        "device": "format-2",
        "type": "mount",
        "id": "mount-1"
      },
      {
        "path": "/boot/efi",
        "device": "format-1",
        "type": "mount",
        "id": "mount-0"
      }
    ]

    Another exception was thrown: type 'Null' is not a subtype of type 'String'

**Comment by dbungert** [comment]
I misspoke earlier, I was thinking of only my own changes.
There are other changes outside of the annotations, raid related things.

**Comment by dbungert** [comment]
JP has a few fixes on Subiquity that sound beneficial.  Should we bring those over on this branch or would you prefer to wait?

**Review by jpnurmi — APPROVED** [review]
LGTM. No issues with the disk space allocation page.

**Comment by jpnurmi** [comment]
> Should we bring those over on this branch or would you prefer to wait?

The timeout fix would be nice to have but we can take it separately

**Pull request merged**
