### PR TITLE
No space available: new layout

### LINKED ISSUE #1629: Redesign no space available screen
The current no space available screen is very dry and dismissive:

grafik

I'd propose to make it a bit more prominent and improve copy and scannability. 

grafik

### PR DESCRIPTION
**Pull request by d-loose**
| Dark | Light |
| - | - |
| image | image |

Close #1629

### CODE REVIEW

**Comment by jpnurmi** [comment]
LGTM! :+1:

**Comment by elioqoshi** [comment]
The icon is a bit too large. Can you make it 33% smaller approximately? Also please check that the icon color is gray, not black/dark gray (similar to other icons).

Apart that, this is good to go :)

Mockup for reference:

grafik

**Comment by d-loose** [comment]
image

**Comment by jpnurmi** [comment]
Artistic touch!

**Comment by d-loose** [comment]
Combining two screenshots in gimp is faster than making a markdown table on github

**Comment by elioqoshi** [comment]
Scarface approves 
grafik

**Review by elioqoshi — APPROVED** [review]

**Review by jpnurmi — APPROVED** [review]
Thanks! LGTM :+1:

**Pull request merged**
