### PR TITLE
Add WSL Select language page

### PR DESCRIPTION
**Pull request by jpnurmi**
Screenshot from 2021-08-27 13-30-09

Close: #155

### CODE REVIEW

**Comment by oSoMoN** [comment]
On my system (default locale is fr_FR.UTF-8), when running the WSL setup wizard, French is listed in the list of languages, but not selected by default, unlike in the desktop installer. Also, manually selecting it doesn't switch the UI to French (I would expect at least the "Go Back" and "Continue" buttons to be translated).

**Comment by jpnurmi** [comment]
> On my system (default locale is fr_FR.UTF-8), when running the WSL setup wizard, French is listed in the list of languages, but not selected by default, unlike in the desktop installer.

Ok, I'll check.

> Also, manually selecting it doesn't switch the UI to French (I would expect at least the "Go Back" and "Continue" buttons to be translated).

There are no translations yet. Only language names are shared between the apps.

**Comment by oSoMoN** [comment]
> There are no translations yet. Only language names are shared between the apps.

We should probably consider sharing common strings, such as "Go Back" and "Continue".

**Comment by jpnurmi** [comment]
> On my system (default locale is fr_FR.UTF-8), when running the WSL setup wizard, French is listed in the list of languages, but not selected by default, unlike in the desktop installer.

The difference was that the Desktop Installer does a language code comparison and the WSL Setup does a full locale comparison. Neither is correct... :point_right: https://github.com/canonical/ubuntu-desktop-installer/pull/289

**Pull request merged**
