### PR TITLE
Choose your look: remove theme descriptions

### PR DESCRIPTION
**Pull request by jpnurmi**
They are not suitable for translation.

Close: #483

### CODE REVIEW

**Comment by jpnurmi** [comment]
The page is not visible in today's installer. The route was commented out in #404.

**Review by oSoMoN — APPROVED** [review]
LGTM, thanks!

**Comment by elioqoshi** [comment]
@jpnurmi This is great, thanks! Would there be any opportunity to change the size of the selection buttons as well?

**Comment by elioqoshi** [comment]
I was just thinking we are not utilizing all the space we have there. Maybe: 
grafik

or

grafik

**Comment by Feichtmeier** [comment]
YaruImageTile could be used for @elioqoshi 's suggestion, even if it is not very hard to create it on your own :)

https://github.com/ubuntu/yaru_widgets.dart/blob/main/lib/src/yaru_image_tile.dart

(even if the selection color should be less transparentized)
grafik
grafik

If yet another dep should be avoided you can ofc just copy paste the code :)

**Comment by jpnurmi** [comment]
@Feichtmeier Looks very nice! Do you want to take this over? I was struggling with the looks and wouldn't mind at all :D

**Comment by Feichtmeier** [comment]
@jpnurmi sure I can :+1: 
Would probably be a good opportunity to finally make a first pub release for yaru_widgets.dart

**Comment by jpnurmi** [comment]
Awesome, thanks!

**Pull request closed without merging**
