### PR TITLE
Add .arb stub files

### PR DESCRIPTION
**Pull request by jpnurmi**
Generated from Ubiquity/d-i's languagelist file: https://git.launchpad.net/ubiquity/tree/d-i/source/localechooser/languagelist

### CODE REVIEW

**Review by seb128 — APPROVED** [review]
Without reviewing the detail of the locales added it seems alright in principle, we can always tweak later if needed. One detail, in the arbgen README you are coding your username in the examples, which is fine but perhaps use ~ instead?

**Comment by jpnurmi** [comment]
It bothers me a bit that there's a massive amount of unused fallback ARB files (`ubuntu_fi.arb`, `ubuntu_fr.arb`, ...).

I'm going to file a Flutter proposal to let one specify a full `@@locale` in the base file, as it was before flutter/flutter#60185. Meanwhile, perhaps we could simply have a `localeName` field in our ARB files to avoid having to create both `ubuntu_fi.arb` and `ubuntu_fi_FI.arb`?

### Before

ubuntu_fr_FR.arb:
```json
{
  "@@locale": "fr",
  "languageName": ""
}
```

ubuntu_fr_FR.arb:
```json
{
  "@@locale": "fr_FR",
  "languageName": "Français"
}
``` 

### After

ubuntu_fr.arb:
```json
{
  "@@locale": "fr",
  "localeName": "fr_FR"
  "languageName": "Français"
}
```

### Future?

ubuntu_fr.arb:
```json
{
  "@@locale": "fr_FR",
  "languageName": "Français"
}
```

**Comment by jpnurmi** [comment]
> One detail, in the arbgen README you are coding your username in the examples, which is fine but perhaps use ~ instead?

Good catch, thanks!

**Comment by jpnurmi** [comment]
I would prefer to have https://github.com/canonical/ubuntu-desktop-installer/pull/457 in first to get rid of the redundant .arb files before we generate stubs for the remaining languages.

**Comment by jpnurmi** [comment]
This PR is ready to go again. #457 was merged and this has been rebased.

NOTE: This PR does not yet import language strings from Ubiquity.

**Pull request merged**
