### PR TITLE
Replace icon_hard_drive_solid image by a Yaru icon

### PR DESCRIPTION
**Pull request by Jupi007**
- Include `yaru_icons` into `pubspec.yaml` ;
- Drop `icon_hard_drive_solid.png` and `2.0x/icon_hard_drive_solid.png` ;
- Use `drive_harddisk` from `YaruIcons` in replacement of `icon_hard_drive_solid.png` into `allocate_disk_space_page.dart`

**Before:**

Capture d’écran du 2021-07-13 15-47-04

**After:**

Capture d’écran du 2021-07-12 21-21-30

_Note: `YaruIcons` are 24x24 with 2px padding by default (same as `Material Icons`)._

CC @Feichtmeier

### CODE REVIEW

**Comment by Jupi007** [comment]
Strange because I signed Canonical CLA just before send this PR 🤔

**Comment by Feichtmeier** [comment]
> Strange because I signed Canonical CLA just before send this PR thinking

Maybe the e-mail addresses do not match?

And thanks for the yaru icon, looks much better :+1:

**Comment by jpnurmi** [comment]
```
Checking the following users on GitHub:
- Jupi007 ✕ (has not signed the CLA)

Checking the following users on Launchpad:
- paul.kepinski@orange.fr ✕ (has not signed the CLA)

Error: CLA Check - FAILED
```

**Comment by MarcusTomlinson** [comment]
> Strange because I signed Canonical CLA just before send this PR 🤔

It can take a day or two to be added to https://github.com/CanonicalContributorAgreement

**Comment by oSoMoN** [comment]
LGTM, and the CLA check now passes. Thanks @Jupi007 !

**Pull request merged**
