### PR TITLE
feat: control page navigation options in routes

### PR DESCRIPTION
**Pull request by d-loose**
Moves the control over whether or not the next/previous buttons are enabled from the pages to the `WizardRoute` using the `userData` property.

### CODE REVIEW

**Comment by d-loose** [comment]
Oh wait.. pages should be able to at least control whether we can proceed or not

**Review by jpnurmi — COMMENTED** [review]
The patch looks great but I'm wondering about the important things like naming because camel-case with short words makes it looks like AlTeRnAtInG cApS... :) Could they be called `hasNext` and `hasPrevious`? because they basically override `Wizard.hasNext` and `Wizard.hasPrevious`?

**Comment by d-loose** [comment]
:+1: yEs, gOOd PoINt!

**Review by jpnurmi — APPROVED** [review]
LGTM :+1:

**Pull request merged**
