### PR TITLE
Use subiquity's languagelist

### PR DESCRIPTION
**Pull request by jpnurmi**
image

Ref: #401

### CODE REVIEW

**Comment by gunnarhj** [comment]
Please No!

The proper languagelist in the desktop installer is a list which represents the languages in Ubuntu's language packs. Whether subiquity strings have (yet) been translated into respective language should not be a criterion.

**Comment by jpnurmi** [comment]
This was originally proposed as a stop-gap solution to get more languages on the list, but we have now generated lots of .arbs to populate the list: https://github.com/canonical/ubuntu-desktop-installer/pull/456.

**Comment by gunnarhj** [comment]
Ok, that makes more sense. But not understanding 3-letter language codes seems as a Flutter bug which should be fixed.

**Comment by jpnurmi** [comment]
Agreed, I opened https://github.com/flutter/flutter/issues/92818 earlier.

**Pull request closed without merging**
