### PR TITLE
Fix typo in Russian

### PR DESCRIPTION
**Pull request by maxunof**

### CODE REVIEW

**Comment by oSoMoN** [comment]
Thanks @maxunof, that looks correct.
Could you please sign [the Canonical CLA](https://ubuntu.com/legal/contributors) to enable us to merge your fix?

**Comment by vitalkanev** [comment]
My fault. I love making typos when typing on my laptop keyboard 😄

**Comment by maxunof** [comment]
I signed the CLA.

**Comment by jpnurmi** [comment]
Thanks! I tried re-running the CLA check but it didn't pass yet. It might take a day or two to sync.

**Comment by oSoMoN** [comment]
@maxunof I'm sorry that we haven't merged your typo fix yet, but it looks like the CLA check is still failing:

    Checking the following users on GitHub:
    - maxunof ✕ (has not signed the CLA)

    Checking the following users on Launchpad:
    - maxunof@pm.me ✕ (has no Launchpad account)

Is your e-mail address correctly associated to your Launchpad account (if you have one)?

**Comment by maxunof** [comment]
I do not know why your bot does not pass the CLA check, so I close PR

**Pull request closed without merging**
