### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by vitalkanev**
Some of the strings were copied from Ubiquity. I know.

Might be the first real PR after #24 got merged.

### CODE REVIEW

**Review by oSoMoN — CHANGES_REQUESTED** [review]
Thank you for the contribution @vitalkanev.
Would you mind merging the latest origin/main into your branch?
You will also need one minor update to reflect the changes in https://github.com/canonical/ubuntu-desktop-installer/commit/d49c6a078bc16aa6f0921febba75301e1db7e236.

**Comment by oSoMoN** [comment]
Also, according to cla-check, you haven't [signed the Canonical CLA](https://ubuntu.com/legal/contributors). Would you mind doing that?

**Comment by vitalkanev** [comment]
> 
> 
> Also, according to cla-check, you haven't [signed the Canonical CLA](https://ubuntu.com/legal/contributors). Would you mind doing that?

CLA signed. Tried to reply using email, but that did not work.

**Comment by MarcusTomlinson** [comment]
> CLA signed.

Thanks @vitalkanev, please allow a couple days to be added to the [CanonicalContributorAgreement](https://github.com/CanonicalContributorAgreement) GitHub org.

**Comment by oSoMoN** [comment]
> You will also need one minor update to reflect the changes in [d49c6a0](https://github.com/canonical/ubuntu-desktop-installer/commit/d49c6a078bc16aa6f0921febba75301e1db7e236).

Please do not forget that one, otherwise one string will appear untranslated in the UI.

**Review by oSoMoN — APPROVED** [review]

**Pull request merged**
