### PR TITLE
arbgen: generate ARB files from languagelist and PO files

### PR DESCRIPTION
**Pull request by jpnurmi**
Run `scripts/import-po.sh path/to/ubiquity` to import all translated strings from Ubiquity where the msgid matches any translation in `xxx_en.arb`.

### CODE REVIEW

**Comment by jpnurmi** [comment]
Depends on #457

**Comment by Mejans** [comment]
Hello,
just had a quick look at this.
I would have excepted that the oc_FR file to grow and not shrink 🤔
Is it correct to remove all those lines?

**Comment by jpnurmi** [comment]
For example, to import Ubiquity's languagelist:
```
dart run bin/arbgen.dart ~/Projects/ubuntu/ubiquity/d-i/source/localechooser/languagelist --output ../../packages/ubuntu_wizard/lib/src/l10n --prefix ubuntu
```

Notice that Ubiquity has PO files in several directories. Something like this would import everything:
```
for po in $(find /home/jpnurmi/Projects/ubuntu/ubiquity -name po); do dart run bin/arbgen.dart $po --output ../../packages/ubuntu_desktop_installer/lib/l10n; done
```

I have pushed an example with all generated files to https://github.com/jpnurmi/ubuntu-desktop-installer/tree/arbgen-example.
Screenshot from 2021-11-02 17-55-38

**Comment by jpnurmi** [comment]
Hi @Mejans, the translations are still there in `app_oc.arb`.

**Comment by Mejans** [comment]
Hi @jpnurmi I see -383 lines =/

**Comment by jpnurmi** [comment]
Notice that it's `app_oc.arb` https://github.com/jpnurmi/ubuntu-desktop-installer/blob/arbgen/packages/ubuntu_desktop_installer/lib/l10n/app_oc.arb. You're probably looking at `app_oc_FR.arb` which was deleted.

First, the empty `app_oc.arb` was deleted. Then, `app_oc_FR.arb` was renamed to `app_oc.arb`, and `@@locale` was modified. Unfortunately, Git is not able to visualize the diff in a reasonable way.

**Comment by jpnurmi** [comment]
Weblate will be used for the import. I've made a backup of the arbgen tool here: https://github.com/jpnurmi/arbgen

**Pull request closed without merging**
