### PR TITLE
Experimental systemd support in WSL

### PR DESCRIPTION
**Pull request by CarlosNihelton**
Hello, @jpnurmi !

This PR is quite big, but most of it is about automatic generated files.

Its purpose is to bring the experimental systemd support in WSL we've been developing for the past few days to the OOBE.

That support was integrated into the server in [subiquity PR #1226](https://github.com/canonical/subiquity/pull/1226). To be able to reflect it in the GUI code and avoid breaking the CI, we had to do a [clean up on WSL side](https://github.com/canonical/subiquity/commit/5695da56998b057c1d26654a9e61a514d66af817) but also adequate this project code to some breaking changes introduced in subiquity by the commits [#f316ea5e](https://github.com/canonical/subiquity/commit/f316ea5e066557dd5e4c92096edf4e4d4e4b10df) and [#e5770f02](https://github.com/canonical/subiquity/commit/e5770f029a4bc73fb06fb220b4e465f077b84f7b). That should save you one hour or two of bisecting :smile: 

With that all tests (including integration) must pass. 

Some strings were removed from the `app_en.arb` file in the package `ubuntu_wsl_setup`. And some were added. Those were not translated to the other language files. I'm counting with Weblate on that.

### CODE REVIEW

**Comment by CarlosNihelton** [comment]
CI is failing on `subiquity_client` tests because subiquity was trying to do some `systemd-run --user` command without the user runtime being prepared. I could not reproduce it on bare metal Ubuntu, but got it on WSL running 20.04.4. The fix was:

```bash
 sudo loginctl enable-linger $USER
 sudo systemctl start user@$UID.service
 export XDG_RUNTIME_DIR=/run/user/$UID
```
The screenshot below shows my WSL instance:

image

Should we add those lines in the CI workflow as part of this PR?

**Comment by jpnurmi** [comment]
Nice job! I like the new cleaner looks! :+1:

I have a subiquity update prepared in https://github.com/canonical/ubuntu-desktop-installer/pull/727 that I'd like to get merged first because it requires code changes that are unrelated to this PR. :)

**Comment by jpnurmi** [comment]
The WSL changes are straightforward and look good! :+1:

I've asked Olivier to take a look at https://github.com/canonical/ubuntu-desktop-installer/pull/727 that updates subiquity up until before the WSL changes.

**Comment by CarlosNihelton** [comment]
> The WSL changes are straightforward and look good! 👍
> 
> I've asked Olivier to take a look at #727 that updates subiquity up until before the WSL changes.

Don't you think that will require this to be rebased right after?

**Comment by jpnurmi** [comment]
Yes, we'll need to rebase this but it should be trivial. We can drop all the unrelated storage changes from this PR. :slightly_smiling_face:

**Review by jpnurmi — APPROVED** [review]
LGTM! :+1:

Live installation works with subiquity cad6cca8.

Screenshot from 2022-03-18 11-52-59

**Pull request merged**
